name    'treydock-edac'
version '0.1.0'
source 'git://github.com/treydock/puppet-edac'
author 'treydock'
license 'Apache License, Version 2.0'
summary 'Manage EDAC utility installation and configuration'
description 'Manage EDAC utility installation and configuration'
project_page 'http://github.com/treydock/puppet-edac'
dependency 'puppetlabs/stdlib', '>=3.2.0 <5.0.0'
dependency 'theforeman/concat_native', '1.x'
